config/routes.rb
Enar::Application.routes.draw do
  devise_for :users
  
  get "fichas/search" => "fichas#search", as: :search_fichas
  
  resources :fichas

  root to: "fichas#index"
end

app/models/ficha.rb
class Ficha < ActiveRecord::Base
  validates :nome, presence: true
  validates :numero_ordem, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fichas_controller.rb
class FichasController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /fichas
  # GET /fichas.json
  def index
    @fichas = Ficha.order(:nome).paginate(per_page: 10, page: params[:page]).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fichas.to_json }
      format.pdf do
        @fichas = Ficha.order(:nome)
        render pdf: Ficha.model_name.human(count: 2),
        layout: 'pdf.html'
      end
    end
  end

  # GET /fichas/1
  # GET /fichas/1.json
  def show
    @ficha = Ficha.find(params[:id])
    
    respond_to do |format|      
      format.html # show.html.erb
      format.json { render json: @ficha }  
    end
  end
  

  # GET /fichas/search?name=fulano
  def search
    @fichas = Ficha.where('nome LIKE ?', "#{params[:name]}%").paginate(per_page: 10, page: params[:page])
    
    respond_to do |format|
      if @fichas.empty?
        flash[:error] = "Nenhum <strong>#{params[:name].to_s}</strong> foi encontrado"
        format.html { redirect_to action: "index" }
      elsif @fichas.size == 1
        @ficha = @fichas.first
        format.html { render action: "show" }
        format.json { render json: @ficha }
      else
        format.html
      end
    end
  end

  # GET /fichas/new
  # GET /fichas/new.json
  def new
    @ficha = Ficha.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ficha }
    end
  end

  # GET /fichas/1/edit
  def edit
    @ficha = Ficha.find(params[:id])
  end

  # POST /fichas
  # POST /fichas.json
  def create
    @ficha = Ficha.new(params[:ficha])
    respond_to do |format|
      if @ficha.save
        if(params[:commit] == "Criar e continuar")
          format.html { redirect_to new_ficha_url, notice: 'Ficha criada com sucesso.' }
        else
          format.html { redirect_to @ficha, notice: 'Ficha criada com sucesso.' }
        end
        format.json { render json: @ficha, status: :created, location: @ficha }
      else
        format.html { render action: "new" }
        format.json { render json: @ficha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fichas/1
  # PUT /fichas/1.json
  def update
    @ficha = Ficha.find(params[:id])

    respond_to do |format|
      if @ficha.update_attributes(params[:ficha])
        format.html { redirect_to @ficha, notice: 'Ficha alterada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ficha.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fichas/1
  # DELETE /fichas/1.json
  def destroy
    @ficha = Ficha.find(params[:id])
    @ficha.destroy

    respond_to do |format|
      format.html { redirect_to fichas_url }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def pagination_links(collection, options = {})
      options[:renderer] ||= BootstrapPaginationHelper::LinkRenderer
      options[:class] ||= 'center-block'
      options[:inner_window] ||= 2
      options[:outer_window] ||= 1
      will_paginate(collection, options)
    end
end

app/helpers/fichas_helper.rb
module FichasHelper
end

app/views/fichas/_form.html.erb
<%= simple_form_for(@ficha, html: {class: "form", role: "form"}) do |f| %>
<%= f.error_notification %>

<div class="form-group row">
  <%= f.input :nome, label: "Nome: ", input_html: {class: "form-control"}, wrapper_html: {class: "col-xs-12 col-md-4"} %>
</div><!-- .form-group -->
<div class="form-group row">
  <%= f.input :numero_ordem, label: "Número de Ordem: ", input_html: {class: "form-control"}, wrapper_html: {class: "col-xs-12  col-md-4"} %>
</div><!-- .form-group -->
<div class="form-group row">
  <%= f.input :admissao, label: "Data de Admissão: ", start_year: 1950, end_year: Date.today.year, input_html: {class: "form-control date-input date-day"}, wrapper_html: {class: 'col-xs-12'} %>
</div><!-- .form-group -->
<div class="form-group row">
  <%= f.input :dispensa, label: "Data de Dispensa: ", start_year: 1950, end_year: Date.today.year, input_html: {class: "form-control date-input"}, wrapper_html: {class: 'col-xs-12'} %>
</div><!-- .form-group -->
<%= f.button :submit, "Criar e continuar", class: "btn btn-primary" unless( params[:action] == "edit" || params[:action] == 'update') %>
<%= f.button :submit, class: "btn #{'btn-primary' if(params[:action] == 'edit' || params[:action] == 'update')}" %>
<% end %>

app/views/fichas/edit.html.erb
<h1>Editando ficha <%= @ficha.numero_ordem%></h1>

<%= render 'form' %>
<br />
<%= link_to 'Mostrar', @ficha %> |
<%= link_to 'Voltar', fichas_path  %>

app/views/fichas/index.html.erb
<h1>Todas as fichas <%= link_to "<span class='glyphicon glyphicon-download'></span> PDF".html_safe, fichas_path(format: "pdf"), class: "btn btn-default", target: "_blank" %></h1>
<table class="table table-striped table-hover">
  <tr class="row">
    <th></th>
    <th>Nome</th>
    <th>Numero ordem</th>
    <th class="visible-lg">Admissao</th>
    <th class="visible-lg">Dispensa</th>
    <th></th>
  </tr>

  <% @fichas.each do |ficha| %>
  <tr class="clickable-row row" data-link=<%= ficha_url(ficha) %>>
    <td class='col-xs-1'>
      <%= link_to "<span class='glyphicon glyphicon-pencil'></span>".html_safe, edit_ficha_path(ficha), class: "btn btn-default btn-xs" %>
    </td>
    <td class="col-xs-5 col-lg-3"><%= ficha.nome %></td>
    <td class="col-xs-5 col-lg-3"><%= ficha.numero_ordem %></td>
    <td class="visible-lg col-lg-2"><%= ficha.admissao.strftime("%d/%m/%Y") if ficha.admissao %></td>
    <td class="visible-lg col-lg-2"><%= ficha.dispensa.strftime("%d/%m/%Y") if ficha.dispensa %></td>
    <td class='col-xs-1'>
      <%= link_to "<span class='glyphicon glyphicon-remove'></span>".html_safe, ficha, confirm: 'Tem Certeza?', method: :delete, class: "btn btn-danger btn-xs"%>        
    </td>
  </tr>
  <% end %>
</table>

<%= link_to "<span class='glyphicon glyphicon-plus'></span> Nova Ficha".html_safe , new_ficha_path, class: "btn btn-primary" %>

<%= pagination_links(@fichas) %>

app/views/fichas/index.pdf.erb
<h1 style="float:left">Todas as fichas</h1>
<h2 style="float:right;color:grey;"><%= Date.today.strftime("%d/%m/%Y") %></h2>
<div style="clear:both"></div><!-- .clearfix -->
<table>
  <tr>
    <th>Nome</th>
    <th>Numero ordem</th>
    <th>Admissao</th>
    <th>Dispensa</th>
  </tr>

<% @fichas.each do |ficha| %>
  <tr>
    <td><%= ficha.nome %></td>
    <td><%= ficha.numero_ordem %></td>
    <td><%= ficha.admissao.strftime("%d/%m/%Y") if ficha.admissao %></td>
    <td><%= ficha.dispensa.strftime("%d/%m/%Y") if ficha.dispensa %></td>
  </tr>
<% end %>
</table>

app/views/fichas/new.html.erb
<h1>Nova ficha</h1>
<%= render 'form' %>
<br />
<%= link_to 'Voltar', fichas_path %>

app/views/fichas/search.html.erb
<h1>Fichas encontradas para: <span class="text-info"><%= params[:name]%></span></h1>
<table class="table table-striped table-hover">
  <tr class="row">
    <th></th>
    <th>Nome</th>
    <th>Numero ordem</th>
    <th class="visible-lg">Admissao</th>
    <th class="visible-lg">Dispensa</th>
    <th></th>
  </tr>

  <% @fichas.each do |ficha| %>
  <tr class="clickable-row row" data-link=<%= ficha_url(ficha) %>>
    <td class='col-xs-1'>
      <%= link_to "<span class='glyphicon glyphicon-pencil'></span>".html_safe, edit_ficha_path(ficha), class: "btn btn-default btn-xs" %>
    </td>
    <td class="col-xs-5 col-lg-3"><%= ficha.nome %></td>
    <td class="col-xs-5 col-lg-3"><%= ficha.numero_ordem %></td>
    <td class="visible-lg col-lg-2"><%= ficha.admissao.strftime("%d/%m/%Y") if ficha.admissao %></td>
    <td class="visible-lg col-lg-2"><%= ficha.dispensa.strftime("%d/%m/%Y") if ficha.dispensa %></td>
    <td class='col-xs-1'>
      <%= link_to "<span class='glyphicon glyphicon-remove'></span>".html_safe, ficha, confirm: 'Tem Certeza?', method: :delete, class: "btn btn-danger btn-xs"%>        
    </td>
  </tr>
  <% end %>
</table>

<%= link_to "<span class='glyphicon glyphicon-plus'></span> Nova Ficha".html_safe , new_ficha_path, class: "btn btn-primary" %>

<%= pagination_links(@fichas) %>

app/views/fichas/show.html.erb
<h2>
  <%= @ficha.nome %>
</h2>

<p>
  <b>Numero ordem:</b>
  <%= @ficha.numero_ordem %>
</p>

<p>
  <b>Admissao:</b>
  <%= @ficha.admissao %>
</p>

<p>
  <b>Dispensa:</b>
  <%= @ficha.dispensa %>
</p>

<br />
<%= link_to 'Editar', edit_ficha_path(@ficha), class: "btn btn-primary"  %>
<br />
<br />
<%= link_to 'Voltar', fichas_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg.html_safe, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="row">
      <nav class="navbar-header col-xs-12">
        <div class="col-xs-2">
          <%= link_to "Início", root_path, :class => 'navbar-brand' %>
        </div><!-- .col-xs-2 -->
          <%= form_tag :search_fichas, method: :get, class: "form-fix", role: "search" do |f| %>
          <%= label_tag :name, "Nome do funcionário", class: "sr-only" %>
          <div class="col-xs-8">
            <div class="input-group">
              <%= text_field_tag :name, nil, class: "form-control", placeholder: "Nome do funcionário" %>
              <span class="input-group-btn">
                <%= button_tag "<span class='glyphicon glyphicon-search'></span>".html_safe, class: "btn btn-default", type: "submit" %>
              </span>
            </div><!-- .input-group -->
          </div><!-- .col-xs-7 -->
          <% end %>

        <ul class="nav navbar-nav col-xs-2">
          <% if user_signed_in? %>
          <li>
            <%= link_to('Logout', destroy_user_session_path, :method=>'delete' ) %>        
          </li>
          <% else %>
          <li>
            <%= link_to('Login', new_user_session_path)  %>  
          </li>
          <% end %>
        </ul>
      </nav>
    </div><!-- .row -->
  </header>

app/views/layouts/application.html.erb
<!doctype html>
<html ng-app='enar'>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Enar" %></title>
  <meta name="description" content="Adm Enar">
  <meta name="author" content="Ri5">
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <div role="main">
    <div class="container">
      <div class="content">
        <%= render 'layouts/messages' %>
        <div ng-view></div>
      </div>
    </div> <!--! end of .container -->
  </div> <!-- main -->
</body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  </head>
  <body>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>